// VectDB Live Demo - WASM Module
//
// Copyright (c) 2025 Michael A. Wright
// Licensed under the MIT License (see LICENSE file)

use wasm_bindgen::prelude::*;
use web_sys::{console, Document, HtmlElement, Window};

// Canned demo data representing search results
const DEMO_DATA: &str = r#"[
    {
        "source": "examples/documents/rust_programming.txt",
        "chunk_index": 0,
        "content": "Rust is a systems programming language that focuses on safety, speed, and concurrency. It achieves memory safety without using a garbage collector, making it ideal for performance-critical applications. Key features include ownership system, zero-cost abstractions, and powerful pattern matching.",
        "similarity": 0.92
    },
    {
        "source": "examples/documents/vector_databases.md",
        "chunk_index": 2,
        "content": "Vector databases use specialized index structures like HNSW (Hierarchical Navigable Small World), IVF (Inverted File Index), or FAISS to organize vectors for efficient search. Queries are converted to vectors and compared using distance metrics such as cosine similarity, Euclidean distance, or dot product.",
        "similarity": 0.87
    },
    {
        "source": "examples/documents/machine_learning_basics.txt",
        "chunk_index": 3,
        "content": "Machine learning algorithms learn from labeled training data in supervised learning. The system learns to map inputs to outputs based on example input-output pairs. Common applications include classification (spam detection, image recognition) and regression (house prices, stock prices).",
        "similarity": 0.81
    },
    {
        "source": "examples/documents/rust_programming.txt",
        "chunk_index": 2,
        "content": "Rust makes it easier to write concurrent programs by preventing data races at compile time. The type system ensures that shared data is properly synchronized. Tools like Cargo handle dependencies, builds, tests, and documentation generation.",
        "similarity": 0.78
    },
    {
        "source": "examples/documents/vector_databases.md",
        "chunk_index": 0,
        "content": "A vector database is a specialized database designed to store and query high-dimensional vectors efficiently. These vectors are typically embeddings generated by machine learning models that represent semantic meaning of text, images, or other data.",
        "similarity": 0.75
    }
]"#;

#[wasm_bindgen(start)]
pub fn main() {
    console::log_1(&"VectDB Demo WASM loaded".into());
}

#[wasm_bindgen]
pub fn search_demo(query: &str) -> String {
    console::log_1(&format!("Demo search for: {}", query).into());

    // For demo purposes, always return the same canned results
    // In a real implementation, this would filter/rank based on the query
    DEMO_DATA.to_string()
}

#[wasm_bindgen]
pub fn get_stats_demo() -> String {
    r#"{
        "document_count": 3,
        "chunk_count": 15,
        "embedding_count": 15,
        "db_size_bytes": 524288
    }"#.to_string()
}

fn get_window() -> Window {
    web_sys::window().expect("no global window exists")
}

fn get_document() -> Document {
    get_window().document().expect("should have a document")
}

#[wasm_bindgen]
pub fn get_element_by_id(id: &str) -> Option<HtmlElement> {
    get_document().get_element_by_id(id)?.dyn_into::<HtmlElement>().ok()
}
